tools check forBug 823062 - hamsta: (stable) kexec-tools not installed when reinstallation via kexec is choosen

diff --git a/tools/qa_tools/qa_tools/setupgrubforinstall b/tools/qa_tools/qa_tools/setupgrubforinstall
--- a/tools/qa_tools/qa_tools/setupgrubforinstall
+++ b/tools/qa_tools/qa_tools/setupgrubforinstall
@@ -127,6 +127,10 @@ fi
 boottype="$1"
 if [ "$boottype" = "kexecboot" ]; then
 	# start the installation with kexec
+	if [ ! -e '/sbin/kexec' ]; then
+	echo "Could not find kexec-utils package"
+	exit 1
+	fi
 	params=`echo $params |sed "/$boottype/s/$boottype //g"`
 	comments="
 	echo \"Install booting by Kexec\"
