Add location-specific qa-config support
Now we can have files like /etc/qa/00-network.<location>, which will be used
only in specific location.

We'll use it for reinstall and other features

diff --git a/libs/qa_lib_config/qa_lib_config/config b/libs/qa_lib_config/qa_lib_config/config
--- a/libs/qa_lib_config/qa_lib_config/config
+++ b/libs/qa_lib_config/qa_lib_config/config
@@ -23,38 +23,6 @@
 # ****************************************************************************
 #
 
-
-SUBMODULE=""
-PART="$1"
-[ -z "$PART" ] || SUBMODULE="${PART}_"
-
-# needed if we re-source this file - cleanup before reading it again
-if [ ! -z "$full_qa_config" ] ; then
-	for var in `echo "$full_qa_config" | sed 's/=.*//'` ; do
-		unset $var
-	done
-fi
-
-# read all configs in correct order
-set > /tmp/$$.before # read all variables before we processed qa config
-for file in /etc/qa/*
-do
-	if [ -f "$file" -a -r "$file" ]
-	then
-		# do not source rpmsave files
-		echo "$file" | grep -q '\.rpmsave$' || source "$file"
-	fi
-done
-unset file
-
-[ -r ~/.qarc ] && source ~/.qarc
-
-set > /tmp/$$.after # read all variables after we processed qa config
-
-full_qa_config=`diff /tmp/$$.before /tmp/$$.after | grep "^>" | sed 's/^> //' | grep -v "^_=\|PIPESTATUS"`
-
-rm /tmp/$$.after /tmp/$$.before
-
 #
 # Helper functions
 #
@@ -72,4 +40,56 @@ function get_qa_config
 	eval echo \$$SUBMODULE$1 
 }
 
+# The code starts here
 
+SUBMODULE=""
+PART="$1"
+[ -z "$PART" ] || SUBMODULE="${PART}_"
+
+# needed if we re-source this file - cleanup before reading it again
+if [ ! -z "$full_qa_config" ] ; then
+	for var in `echo "$full_qa_config" | sed 's/=.*//'` ; do
+		unset $var
+	done
+fi
+
+# read all configs in correct order
+set > /tmp/$$.before # read all variables before we processed qa config
+for file in /etc/qa/*
+do
+	# skip (invalid/all)location files
+	if [ -z "$location_qa_config" ] && echo $file | grep '\.' ; then
+		# Dots are allowed only in location-specific configurations
+		# but we are reaading only globals now
+		continue
+	elif echo $file | grep '\.' && echo $file | grep -v "\.$location_qa_config$" ; then
+		# It is location faile but for different location
+		continue
+	fi
+
+	# seems to be ok to read it (if it is readable)
+	if [ -f "$file" -a -r "$file" ]
+	then
+		# do not source rpmsave files
+		echo "$file" | grep -q '\.rpmsave$' || source "$file"
+	fi
+done
+unset file
+
+[ -r ~/.qarc ] && source ~/.qarc
+
+set > /tmp/$$.after # read all variables after we processed qa config
+
+full_qa_config=`diff /tmp/$$.before /tmp/$$.after | grep "^>" | sed 's/^> //' | grep -v "^_=\|PIPESTATUS"`
+
+rm /tmp/$$.after /tmp/$$.before
+
+
+# Now try the location specific things unelss we already did so befere (recursion of sourcing)
+if [ -z "$location_qa_config" ] ; then
+	location_qa_config="$location"  # read from config files!
+	[ -z "$location_qa_config" -a -x '/usr/share/qa/tools/location_detect.impl' ] && location_qa_config="`/usr/share/qa/tools/location_detect.impl`"
+
+	# ok we have defined location, re-read it all again and now do it correctly
+	[ -z "$location_qa_config" ] || source /usr/share/qa/lib/config "$PART"
+fi	
